#!/usr/bin/env python3
import argparse
import vlc

from search import searchForSongs
from player import playAudio
from utils import displayResultsTable, playBackControls, startVisualizer, stopVisualizer
from rich.prompt import Prompt
from rich.console import Console

console = Console()

parser = argparse.ArgumentParser(description="🎧 ShellBeats - Terminal Music Player")

parser.add_argument("query", nargs="+", default="Metallica", type=str, help="Search query (e.g., 'john mayer')")
parser.add_argument("limit", nargs="?", default=5, type=int, help="Number of videos to search")

args = parser.parse_args()
 
res = searchForSongs(" ".join(args.query), args.limit)

displayResultsTable(res)

choice = Prompt.ask("Enter your choice: ", choices=[str(i+1) for i in range(args.limit)])
choice = int(choice)
choice_url = res[choice-1]['link'] 
with console.status("⏳ Extracting stream and starting playback...", spinner="dots"):
    url = playAudio(choice_url) 
title = res[choice-1]['title']
player = vlc.MediaPlayer(url)
player.play()
startVisualizer(title)

playBackControls(player)
stopVisualizer()